name: Create Release on PR

on:
  pull_request:
    types:
      - closed

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Get PR title
        run: |
          PR_TITLE=$(curl -sSL https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r '.title')
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Get UpdateVers Script
        run: echo "${{ vars.UPDATE_VERS_SCRIPT }}" > updateVers.py
        shell: bash

      - name: Update Version
        run: |
          NEW_VERS=$(python updateVers.py '${{ steps.get-latest-tag.outputs.tag }}' '${{ env.PR_TITLE }}')
          echo "NEW_VERS=$NEW_VERS" >> $GITHUB_ENV
        id: create-next-tag

      - name: Get Commit SHA of Merged PR
        run: |
          PR_MERGE_SHA=$(curl -sSL https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge | jq -r '.sha')
          echo "PR_MERGE_SHA=$PR_MERGE_SHA" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git tag -f -a '${{ env.NEW_VERS }}' '${{ github.sha }}' -m 'Creato tag.'
          git push -f origin '${{ env.NEW_VERS }}'

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_VERS }}
          release_name: ${{ env.NEW_VERS }}
          body: ${{ env.PR_TITLE }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
